name: Custom check report
on:
  workflow_dispatch:

jobs:
  report_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Report custom check
        run: |
          pip install -r requirements.txt
          python report.py
        env:
          OPSLEVEL_API_TOKEN: '${{ secrets.OPSLEVEL_API_TOKEN }}' 
